sudo: false
language: ruby
rvm:
- 2.3.0
before_install: gem install bundler -v 1.12.5
env:
  matrix:
    secure: n+qvS/V5ZeCZ15RMNPeTxtAd+79XZniWNoYCriGtrJkELt/7bc4teXB8thowXHrm4Sx2lHW9uE8cR2s56RyRoV0PQU+nenjylAHPkfwlu/isutw3PGGFJoF3O89bG5jtQCQcequSH+PHRLc0xYoKaRLOMEuO0RPzd+hALt3jobzs5Q4hvvFinF8yDOTG0Qo24CtvZqNMAz0QtkWJExIZ8i2G7DnkY7Jy6DaJjv+A3MdTe2xTikSjWOvFjMrRVd1v+aP9gUTNVTy5aahpKSwub7TzsS/yj8rSI8717As/sSxepWXBg1N1AnrH6ttgjpdyjELXYlTrCx01u4sQMW3HRKG4WJzSVKaQ9W6fF82TQySh6hAaiO5/HYZ73+TTCnEk6eFJT/FaT7yNyOwhRA2Wq091PVFgfZOFy+Hxbj3dWVZm0hS5odaQ5c/aUYR8EiyfUwgHQQxl2QYjUMci+5QOa5k5TmqBHq4iqa0khC5t/zbCvY5ImC4/ySTtIQZnAtHxh3ZhdrukQn0LgLQ4BKVGZEz0wyiaMQrkf8XUgv5pkegTcAhkaz7vZs5j0wtY6CV0q9t5D2n8Xj9amo3SOfTtJjOLZ3xBJhjJRr4J219wN0EFtHt+3rXVoKcw3Vz1ysyV1Jn2B68LF0LPHwSFKDGqptP3axBJNs/utGcDTHAx8hU=
